/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIDecisionLog {
  'executionDetails' : [] | [
    {
      'slippagePct' : number,
      'feePct' : number,
      'executionDelayMs' : bigint,
      'spreadPct' : number,
    }
  ],
  'indicatorValues' : {
    'atr' : number,
    'rsi' : number,
    'bollingerBandwidth' : number,
    'macd' : number,
    'ema20' : number,
    'ema50' : number,
  },
  'decision' : TradeDecision,
  'noTradeReason' : [] | [string],
  'decisionCycleId' : bigint,
  'alternativesConsidered' : Array<[string, number]>,
  'skipReason' : [] | [string],
  'executionStatus' : { 'Skipped' : null } |
    { 'Failed' : null } |
    { 'Executed' : null } |
    { 'Pending' : null },
  'multiTimeframeSignals' : Array<
    {
      'rsi' : number,
      'macdSignal' : { 'Bearish' : null } |
        { 'Cross' : null } |
        { 'Bullish' : null },
      'trend' : { 'Bearish' : null } |
        { 'Neutral' : null } |
        { 'Bullish' : null },
      'timeframe' : string,
      'emaAlignment' : boolean,
      'strength' : number,
    }
  >,
  'marketSnapshot' : {
    'btcDominance' : number,
    'volume24h' : number,
    'volatilityPct' : number,
    'price' : number,
  },
  'executedTradeId' : [] | [string],
  'confidenceFactors' : {
    'regimeConfidence' : number,
    'total' : number,
    'trendAlignment' : number,
    'liquidity' : number,
    'momentum' : number,
    'marketStructure' : number,
    'historicalSetupPerformance' : number,
    'volatilityQuality' : number,
  },
}
export interface AITrainingState {
  'confidenceThreshold' : number,
  'correlationData' : Array<CorrelationData>,
  'marketMemory' : Array<StrategyPerformanceByRegime>,
  'lastTrainingUpdate' : bigint,
  'avgConfidenceScore' : number,
  'consecutiveLosses' : bigint,
  'strategyPerformances' : Array<
    {
      'totalTrades' : bigint,
      'wins' : bigint,
      'lastUpdated' : bigint,
      'avgConfidence' : number,
      'losses' : bigint,
      'totalPnl' : number,
      'winRate' : number,
      'strategyMode' : { 'Defensive' : null } |
        { 'Observation' : null } |
        { 'TrendFollowing' : null } |
        { 'Scalping' : null } |
        { 'MeanReversion' : null },
    }
  >,
  'overallWinRate' : number,
  'learningProgress' : number,
  'confidenceCalibration' : number,
  'overtradingCount' : bigint,
  'practiceTradesCount' : bigint,
  'totalSessions' : bigint,
  'noTradeLog' : Array<NoTradeDecision>,
}
export interface ActivityItem {
  'action' : string,
  'asset' : string,
  'reasoning' : string,
  'timestamp' : bigint,
  'executed' : boolean,
  'confidence' : number,
}
export interface ArenaResult {
  'tradeCount' : bigint,
  'agentId' : string,
  'avgHoldTime' : bigint,
  'sharpeRatio' : number,
  'performanceByRegime' : Array<RegimeBreakdown>,
  'finalBalance' : number,
  'winRate' : number,
  'totalReturnPct' : number,
  'maxDrawdownPct' : number,
}
export interface ArenaSession {
  'completedAt' : bigint,
  'endDate' : string,
  'results' : Array<ArenaResult>,
  'initialCapital' : number,
  'sessionId' : string,
  'symbol' : string,
  'startDate' : string,
}
export interface AssetBalance {
  'asset' : string,
  'free' : number,
  'locked' : number,
}
export interface BacktestResults {
  'totalTrades' : bigint,
  'trades' : Array<
    {
      'id' : string,
      'pnl' : [] | [number],
      'status' : { 'Open' : null } |
        { 'Closed' : null } |
        { 'TakeProfitHit' : null } |
        { 'StopLossHit' : null } |
        { 'Cancelled' : null },
      'action' : { 'Buy' : null } |
        { 'Hold' : null } |
        { 'Sell' : null } |
        { 'Skip' : null },
      'closeTime' : bigint,
      'pnlPercent' : [] | [number],
      'decisionId' : string,
      'takeProfit' : [] | [number],
      'stopLoss' : number,
      'quantity' : number,
      'entryPrice' : number,
      'exitPrice' : [] | [number],
      'openTime' : bigint,
      'symbol' : string,
    }
  >,
  'sharpeRatio' : [] | [number],
  'finalBalance' : number,
  'equityCurve' : Array<EquityPoint>,
  'totalReturn' : number,
  'winRate' : number,
  'maxDrawdown' : number,
  'totalPnlPercent' : number,
}
export interface BacktestSession {
  'id' : string,
  'status' : BacktestStatus,
  'initialBalance' : number,
  'symbols' : Array<string>,
  'endDate' : bigint,
  'name' : string,
  'results' : [] | [BacktestResults],
  'startDate' : bigint,
}
export type BacktestStatus = { 'Failed' : null } |
  { 'Running' : null } |
  { 'Completed' : null };
export interface BotConfig {
  'partialExitLevels' : Array<PartialExitLevel>,
  'decisionIntervalSecs' : bigint,
  'simulationFidelity' : SimulationFidelity,
  'refreshIntervalSecs' : bigint,
  'startingBalance' : number,
  'tradingMode' : TradingMode,
  'volatilityPositionSizing' : boolean,
}
export interface BotState {
  'status' : BotStatus,
  'startedAt' : [] | [bigint],
  'dataFeedHealthy' : boolean,
  'uptimeSeconds' : bigint,
  'tradesExecutedCount' : bigint,
  'lastDecisionAt' : [] | [bigint],
  'decisionCycleCount' : bigint,
  'lastDataFetchAt' : [] | [bigint],
}
export type BotStatus = { 'Stopped' : null } |
  { 'Paused' : null } |
  { 'EmergencyStopped' : null } |
  { 'Running' : null };
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : bigint,
}
export interface ConfidenceFactors {
  'regimeConfidence' : number,
  'total' : number,
  'trendAlignment' : number,
  'liquidity' : number,
  'momentum' : number,
  'marketStructure' : number,
  'historicalSetupPerformance' : number,
  'volatilityQuality' : number,
}
export interface ConfidencePoint {
  'regime' : string,
  'action' : string,
  'asset' : string,
  'timestamp' : bigint,
  'confidence' : number,
}
export interface CorrelationData {
  'lastUpdated' : bigint,
  'btcCorrelation' : number,
  'symbol' : string,
}
export interface DataFeedStatus {
  'healthy' : boolean,
  'staleSince' : [] | [bigint],
  'lastFetchAt' : [] | [bigint],
  'assetCount' : bigint,
}
export interface DecisionCycleStats {
  'cyclesPerHour' : number,
  'totalCycles' : bigint,
  'avgConfidence' : number,
  'noTradeRate' : number,
  'tradesThisSession' : bigint,
  'winRate' : number,
}
export interface EquityPoint { 'value' : number, 'timestamp' : bigint }
export interface EquitySnapshot {
  'dailyPnLPct' : number,
  'totalPnLPct' : number,
  'realizedPnLToday' : number,
  'cash' : number,
  'positionValue' : number,
  'timestamp' : bigint,
  'unrealizedPnL' : number,
  'equity' : number,
}
export interface ExchangeStatus {
  'exchangeId' : string,
  'connected' : boolean,
  'phase' : bigint,
  'lastTestTimestamp' : bigint,
}
export type MarketCondition = { 'StrongBearish' : null } |
  { 'LowLiquidityDanger' : null } |
  { 'HighVolatility' : null } |
  { 'ManipulationRisk' : null } |
  { 'Ranging' : null } |
  { 'Neutral' : null } |
  { 'WeakBearish' : null } |
  { 'StrongBullish' : null } |
  { 'Bullish' : null };
export interface MarketData {
  'change24h' : number,
  'marketCap' : number,
  'lastUpdated' : bigint,
  'volume24h' : number,
  'price' : number,
  'symbol' : string,
}
export interface MarketSnapshot {
  'btcDominance' : number,
  'totalMarketCap' : number,
  'markets' : Array<MarketData>,
  'timestamp' : bigint,
  'fearGreedIndex' : [] | [number],
}
export interface NoTradeDecision {
  'marketRegime' : MarketCondition,
  'confidenceAtTime' : number,
  'thresholdAtTime' : number,
  'timestamp' : Timestamp,
  'symbol' : Symbol,
  'reason' : NoTradeReason,
}
export type NoTradeReason = { 'OvertradingFlag' : null } |
  { 'ExistingPosition' : null } |
  { 'DrawdownProtection' : null } |
  { 'VolatilityTooHigh' : null } |
  { 'RegimeMismatch' : null } |
  { 'CorrelationLimit' : null } |
  { 'LiquidityTooLow' : null } |
  { 'LowConfidence' : null };
export interface OrderRecord {
  'qty' : number,
  'status' : string,
  'side' : string,
  'orderId' : string,
  'timestamp' : bigint,
  'price' : number,
  'symbol' : string,
}
export type PartialExitLevel = [number, number];
export interface Portfolio {
  'totalTrades' : bigint,
  'dayPnl' : number,
  'dayPnlPercent' : number,
  'totalValue' : number,
  'totalPnl' : number,
  'cashBalance' : number,
  'winningTrades' : bigint,
  'positions' : Array<Position>,
  'winRate' : number,
  'totalPnlPercent' : number,
  'investedValue' : number,
}
export interface Position {
  'currentPrice' : number,
  'averageEntryPrice' : number,
  'takeProfit' : [] | [number],
  'stopLoss' : number,
  'unrealizedPnlPercent' : number,
  'quantity' : number,
  'unrealizedPnl' : number,
  'openTime' : bigint,
  'symbol' : string,
}
export interface RegimeBreakdown {
  'regime' : MarketCondition,
  'returnPct' : number,
  'winRate' : number,
}
export interface RiskEvent {
  'id' : string,
  'message' : string,
  'timestamp' : bigint,
  'severity' : RiskSeverity,
  'eventType' : RiskEventType,
}
export type RiskEventType = { 'EmergencyStop' : null } |
  { 'VolatilityPause' : null } |
  { 'DailyLossLimitHit' : null } |
  { 'ManualPause' : null } |
  { 'ConsecutiveLossesAutopaused' : null } |
  { 'ResumeTrade' : null };
export interface RiskSettings {
  'conservativeMode' : boolean,
  'maxConsecutiveLosses' : bigint,
  'enablePaperTrading' : boolean,
  'emergencyStopEnabled' : boolean,
  'maxDailyLossPercent' : number,
  'maxPositionSizePercent' : number,
}
export type RiskSeverity = { 'Info' : null } |
  { 'Critical' : null } |
  { 'Warning' : null };
export interface RiskStatus {
  'dailyLoss' : number,
  'isPaused' : boolean,
  'consecutiveLosses' : bigint,
  'riskScore' : number,
  'dailyLossPercent' : number,
}
export interface SimulationFidelity {
  'slippagePct' : number,
  'feeTakerPct' : number,
  'feeMakerPct' : number,
  'spreadPct' : number,
}
export interface SimulationStats {
  'avgSlippagePct' : number,
  'avgFeePct' : number,
  'totalSlippageCost' : number,
  'totalSpreadCost' : number,
  'totalFeeCost' : number,
}
export type StrategyMode = { 'Defensive' : null } |
  { 'Observation' : null } |
  { 'TrendFollowing' : null } |
  { 'Scalping' : null } |
  { 'MeanReversion' : null };
export interface StrategyPerformance {
  'totalTrades' : bigint,
  'wins' : bigint,
  'lastUpdated' : bigint,
  'avgConfidence' : number,
  'losses' : bigint,
  'totalPnl' : number,
  'winRate' : number,
  'strategyMode' : StrategyMode,
}
export interface StrategyPerformanceByRegime {
  'lossCount' : bigint,
  'marketCondition' : MarketCondition,
  'totalPnl' : number,
  'winCount' : bigint,
  'avgHoldTimeSeconds' : bigint,
  'strategyMode' : StrategyMode,
  'avgPnl' : number,
}
export type Symbol = string;
export interface TechnicalIndicators {
  'atr' : number,
  'rsi' : number,
  'macdSignal' : number,
  'bollingerMid' : number,
  'trendStrength' : number,
  'macd' : number,
  'momentum' : number,
  'bollingerLower' : number,
  'ema20' : number,
  'ema50' : number,
  'bollingerUpper' : number,
}
export type Timestamp = bigint;
export interface Trade {
  'id' : string,
  'pnl' : [] | [number],
  'status' : TradeStatus,
  'action' : TradeAction,
  'closeTime' : bigint,
  'pnlPercent' : [] | [number],
  'decisionId' : string,
  'takeProfit' : [] | [number],
  'stopLoss' : number,
  'quantity' : number,
  'entryPrice' : number,
  'exitPrice' : [] | [number],
  'openTime' : bigint,
  'symbol' : string,
}
export type TradeAction = { 'Buy' : null } |
  { 'Hold' : null } |
  { 'Sell' : null } |
  { 'Skip' : null };
export interface TradeDecision {
  'id' : string,
  'action' : TradeAction,
  'marketCondition' : { 'StrongBearish' : null } |
    { 'LowLiquidityDanger' : null } |
    { 'HighVolatility' : null } |
    { 'ManipulationRisk' : null } |
    { 'Ranging' : null } |
    { 'Neutral' : null } |
    { 'WeakBearish' : null } |
    { 'StrongBullish' : null } |
    { 'Bullish' : null },
  'targetPrice' : [] | [number],
  'reasoning' : string,
  'riskReward' : number,
  'stopLoss' : number,
  'indicators' : {
    'atr' : number,
    'rsi' : number,
    'macdSignal' : number,
    'bollingerMid' : number,
    'trendStrength' : number,
    'macd' : number,
    'momentum' : number,
    'bollingerLower' : number,
    'ema20' : number,
    'ema50' : number,
    'bollingerUpper' : number,
  },
  'timestamp' : bigint,
  'entryPrice' : number,
  'confidence' : number,
  'strategyMode' : StrategyMode,
  'symbol' : string,
}
export type TradeId = string;
export interface TradeSnapshot {
  'netImpactPct' : number,
  'marketRegimeAtEntry' : MarketCondition,
  'simulatedSpread' : number,
  'simulatedLatencyMs' : bigint,
  'tags' : Array<TradeTag>,
  'aiReasoningText' : string,
  'tradeId' : TradeId,
  'indicatorsAtEntry' : TechnicalIndicators,
  'simulatedFees' : number,
  'simulatedSlippage' : number,
  'volatilityRatio' : number,
  'confidenceFactors' : ConfidenceFactors,
}
export type TradeStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'TakeProfitHit' : null } |
  { 'StopLossHit' : null } |
  { 'Cancelled' : null };
export type TradeTag = { 'GoodScaling' : null } |
  { 'GoodDiscipline' : null } |
  { 'TextbookWin' : null } |
  { 'OvertradeLoss' : null } |
  { 'RegimeMismatch' : null } |
  { 'PrematureExit' : null } |
  { 'TightStop' : null };
export type TradingMode = { 'Autonomous' : null } |
  { 'SignalOnly' : null } |
  { 'Manual' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'applyTradeToTraining' : ActorMethod<[Trade, TradeDecision], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backtestTransform' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'botTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'closePosition' : ActorMethod<
    [string],
    { 'ok' : Trade } |
      { 'err' : string }
  >,
  'emergencyStopBot' : ActorMethod<[], BotState>,
  'executeManualTrade' : ActorMethod<
    [string, string, number],
    { 'ok' : Trade } |
      { 'err' : string }
  >,
  'executePendingDecisions' : ActorMethod<[], Array<Trade>>,
  'fetchAndStoreHistoricalCandles' : ActorMethod<
    [string, bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'fetchMarketData' : ActorMethod<[], Array<MarketData>>,
  'getAIStatus' : ActorMethod<
    [],
    {
      'mode' : string,
      'lastRunTime' : bigint,
      'nextRunTime' : bigint,
      'isRunning' : boolean,
      'cycleCount' : bigint,
    }
  >,
  'getAITrainingState' : ActorMethod<[], AITrainingState>,
  'getAllConfidenceTimeline' : ActorMethod<[bigint], Array<ConfidencePoint>>,
  'getArenaResults' : ActorMethod<[string], [] | [ArenaSession]>,
  'getArenaSessions' : ActorMethod<[], Array<ArenaSession>>,
  'getBacktestSession' : ActorMethod<[string], [] | [BacktestSession]>,
  'getBotConfig' : ActorMethod<[], BotConfig>,
  'getBotState' : ActorMethod<[], BotState>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfidenceTimeline' : ActorMethod<
    [string, bigint],
    Array<ConfidencePoint>
  >,
  'getCurrentEquity' : ActorMethod<[], [] | [EquitySnapshot]>,
  'getCurrentMarketCondition' : ActorMethod<[], [] | [MarketCondition]>,
  'getDataFeedStatus' : ActorMethod<[], DataFeedStatus>,
  'getDecisionCycleStats' : ActorMethod<[], DecisionCycleStats>,
  'getDecisionsByAsset' : ActorMethod<[string, bigint], Array<AIDecisionLog>>,
  'getEquityHistory' : ActorMethod<[bigint], Array<EquitySnapshot>>,
  'getExchangeBalances' : ActorMethod<[string], Array<AssetBalance>>,
  'getExchangeConnections' : ActorMethod<[], Array<ExchangeStatus>>,
  'getExchangeOrderHistory' : ActorMethod<[string], Array<OrderRecord>>,
  'getHistoricalCandles' : ActorMethod<[string, bigint], Array<Candle>>,
  'getLatestDecisions' : ActorMethod<[bigint], Array<AIDecisionLog>>,
  'getLatestSnapshot' : ActorMethod<[], [] | [MarketSnapshot]>,
  'getLiveActivityFeed' : ActorMethod<[bigint], Array<ActivityItem>>,
  'getMarketCandles' : ActorMethod<[string], Array<Candle>>,
  'getMarketMemory' : ActorMethod<[], Array<StrategyPerformanceByRegime>>,
  'getNoTradeLog' : ActorMethod<[], Array<NoTradeDecision>>,
  'getOpenPositions' : ActorMethod<[], Array<Position>>,
  'getPortfolio' : ActorMethod<[], Portfolio>,
  'getRecentDecisions' : ActorMethod<[bigint], Array<AIDecisionLog>>,
  'getRiskEvents' : ActorMethod<[bigint], Array<RiskEvent>>,
  'getRiskSettings' : ActorMethod<[], RiskSettings>,
  'getRiskStatus' : ActorMethod<[], RiskStatus>,
  'getSimulationStats' : ActorMethod<[], SimulationStats>,
  'getStrategyPerformances' : ActorMethod<[], Array<StrategyPerformance>>,
  'getTopSetups' : ActorMethod<[], Array<StrategyPerformanceByRegime>>,
  'getTradeHistory' : ActorMethod<[bigint], Array<Trade>>,
  'getTradeSnapshot' : ActorMethod<[string], [] | [TradeSnapshot]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBacktestSessions' : ActorMethod<[], Array<BacktestSession>>,
  'pauseBot' : ActorMethod<[], BotState>,
  'refreshGlobalData' : ActorMethod<[], [number, number]>,
  'removeExchangeConnection' : ActorMethod<[string], boolean>,
  'resetBot' : ActorMethod<[], BotState>,
  'resetTrainingData' : ActorMethod<[], boolean>,
  'resumeBot' : ActorMethod<[], BotState>,
  'resumeTrading' : ActorMethod<[], boolean>,
  'runAIAnalysis' : ActorMethod<[], Array<AIDecisionLog>>,
  'runDecisionCycle' : ActorMethod<
    [],
    {
        'ok' : {
          'skipped' : bigint,
          'reasoning' : string,
          'decisionsGenerated' : bigint,
          'positionsUpdated' : bigint,
          'tradesExecuted' : bigint,
        }
      } |
      { 'err' : string }
  >,
  'runMarketCycle' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'saveExchangeConnection' : ActorMethod<[string, string, string], boolean>,
  'setAIMode' : ActorMethod<[string], boolean>,
  'startArena' : ActorMethod<[string, string, string], string>,
  'startBacktest' : ActorMethod<
    [string, Array<string>, bigint, bigint, number],
    BacktestSession
  >,
  'startBot' : ActorMethod<[], { 'ok' : BotState } | { 'err' : string }>,
  'testExchangeConnection' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerEmergencyStop' : ActorMethod<[], boolean>,
  'updateBotConfig' : ActorMethod<
    [BotConfig],
    { 'ok' : BotConfig } |
      { 'err' : string }
  >,
  'updateRiskSettings' : ActorMethod<[RiskSettings], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];