/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TradeStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'TakeProfitHit' : IDL.Null,
  'StopLossHit' : IDL.Null,
  'Cancelled' : IDL.Null,
});
export const TradeAction = IDL.Variant({
  'Buy' : IDL.Null,
  'Hold' : IDL.Null,
  'Sell' : IDL.Null,
  'Skip' : IDL.Null,
});
export const Trade = IDL.Record({
  'id' : IDL.Text,
  'pnl' : IDL.Opt(IDL.Float64),
  'status' : TradeStatus,
  'action' : TradeAction,
  'closeTime' : IDL.Int,
  'pnlPercent' : IDL.Opt(IDL.Float64),
  'decisionId' : IDL.Text,
  'takeProfit' : IDL.Opt(IDL.Float64),
  'stopLoss' : IDL.Float64,
  'quantity' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Opt(IDL.Float64),
  'openTime' : IDL.Int,
  'symbol' : IDL.Text,
});
export const StrategyMode = IDL.Variant({
  'Defensive' : IDL.Null,
  'Observation' : IDL.Null,
  'TrendFollowing' : IDL.Null,
  'Scalping' : IDL.Null,
  'MeanReversion' : IDL.Null,
});
export const TradeDecision = IDL.Record({
  'id' : IDL.Text,
  'action' : TradeAction,
  'marketCondition' : IDL.Variant({
    'StrongBearish' : IDL.Null,
    'LowLiquidityDanger' : IDL.Null,
    'HighVolatility' : IDL.Null,
    'ManipulationRisk' : IDL.Null,
    'Ranging' : IDL.Null,
    'Neutral' : IDL.Null,
    'WeakBearish' : IDL.Null,
    'StrongBullish' : IDL.Null,
    'Bullish' : IDL.Null,
  }),
  'targetPrice' : IDL.Opt(IDL.Float64),
  'reasoning' : IDL.Text,
  'riskReward' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'indicators' : IDL.Record({
    'atr' : IDL.Float64,
    'rsi' : IDL.Float64,
    'macdSignal' : IDL.Float64,
    'bollingerMid' : IDL.Float64,
    'trendStrength' : IDL.Float64,
    'macd' : IDL.Float64,
    'momentum' : IDL.Float64,
    'bollingerLower' : IDL.Float64,
    'ema20' : IDL.Float64,
    'ema50' : IDL.Float64,
    'bollingerUpper' : IDL.Float64,
  }),
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Float64,
  'confidence' : IDL.Float64,
  'strategyMode' : StrategyMode,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const BotStatus = IDL.Variant({
  'Stopped' : IDL.Null,
  'Paused' : IDL.Null,
  'EmergencyStopped' : IDL.Null,
  'Running' : IDL.Null,
});
export const BotState = IDL.Record({
  'status' : BotStatus,
  'startedAt' : IDL.Opt(IDL.Nat64),
  'dataFeedHealthy' : IDL.Bool,
  'uptimeSeconds' : IDL.Nat64,
  'tradesExecutedCount' : IDL.Nat,
  'lastDecisionAt' : IDL.Opt(IDL.Nat64),
  'decisionCycleCount' : IDL.Nat,
  'lastDataFetchAt' : IDL.Opt(IDL.Nat64),
});
export const MarketData = IDL.Record({
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'volume24h' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const CorrelationData = IDL.Record({
  'lastUpdated' : IDL.Int,
  'btcCorrelation' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MarketCondition = IDL.Variant({
  'StrongBearish' : IDL.Null,
  'LowLiquidityDanger' : IDL.Null,
  'HighVolatility' : IDL.Null,
  'ManipulationRisk' : IDL.Null,
  'Ranging' : IDL.Null,
  'Neutral' : IDL.Null,
  'WeakBearish' : IDL.Null,
  'StrongBullish' : IDL.Null,
  'Bullish' : IDL.Null,
});
export const StrategyPerformanceByRegime = IDL.Record({
  'lossCount' : IDL.Nat,
  'marketCondition' : MarketCondition,
  'totalPnl' : IDL.Float64,
  'winCount' : IDL.Nat,
  'avgHoldTimeSeconds' : IDL.Int,
  'strategyMode' : StrategyMode,
  'avgPnl' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const Symbol = IDL.Text;
export const NoTradeReason = IDL.Variant({
  'OvertradingFlag' : IDL.Null,
  'ExistingPosition' : IDL.Null,
  'DrawdownProtection' : IDL.Null,
  'VolatilityTooHigh' : IDL.Null,
  'RegimeMismatch' : IDL.Null,
  'CorrelationLimit' : IDL.Null,
  'LiquidityTooLow' : IDL.Null,
  'LowConfidence' : IDL.Null,
});
export const NoTradeDecision = IDL.Record({
  'marketRegime' : MarketCondition,
  'confidenceAtTime' : IDL.Float64,
  'thresholdAtTime' : IDL.Float64,
  'timestamp' : Timestamp,
  'symbol' : Symbol,
  'reason' : NoTradeReason,
});
export const AITrainingState = IDL.Record({
  'confidenceThreshold' : IDL.Float64,
  'correlationData' : IDL.Vec(CorrelationData),
  'marketMemory' : IDL.Vec(StrategyPerformanceByRegime),
  'lastTrainingUpdate' : IDL.Int,
  'avgConfidenceScore' : IDL.Float64,
  'consecutiveLosses' : IDL.Nat,
  'strategyPerformances' : IDL.Vec(
    IDL.Record({
      'totalTrades' : IDL.Nat,
      'wins' : IDL.Nat,
      'lastUpdated' : IDL.Int,
      'avgConfidence' : IDL.Float64,
      'losses' : IDL.Nat,
      'totalPnl' : IDL.Float64,
      'winRate' : IDL.Float64,
      'strategyMode' : IDL.Variant({
        'Defensive' : IDL.Null,
        'Observation' : IDL.Null,
        'TrendFollowing' : IDL.Null,
        'Scalping' : IDL.Null,
        'MeanReversion' : IDL.Null,
      }),
    })
  ),
  'overallWinRate' : IDL.Float64,
  'learningProgress' : IDL.Float64,
  'confidenceCalibration' : IDL.Float64,
  'overtradingCount' : IDL.Nat,
  'practiceTradesCount' : IDL.Nat,
  'totalSessions' : IDL.Nat,
  'noTradeLog' : IDL.Vec(NoTradeDecision),
});
export const ConfidencePoint = IDL.Record({
  'regime' : IDL.Text,
  'action' : IDL.Text,
  'asset' : IDL.Text,
  'timestamp' : IDL.Nat64,
  'confidence' : IDL.Float64,
});
export const RegimeBreakdown = IDL.Record({
  'regime' : MarketCondition,
  'returnPct' : IDL.Float64,
  'winRate' : IDL.Float64,
});
export const ArenaResult = IDL.Record({
  'tradeCount' : IDL.Nat,
  'agentId' : IDL.Text,
  'avgHoldTime' : IDL.Int,
  'sharpeRatio' : IDL.Float64,
  'performanceByRegime' : IDL.Vec(RegimeBreakdown),
  'finalBalance' : IDL.Float64,
  'winRate' : IDL.Float64,
  'totalReturnPct' : IDL.Float64,
  'maxDrawdownPct' : IDL.Float64,
});
export const ArenaSession = IDL.Record({
  'completedAt' : IDL.Int,
  'endDate' : IDL.Text,
  'results' : IDL.Vec(ArenaResult),
  'initialCapital' : IDL.Float64,
  'sessionId' : IDL.Text,
  'symbol' : IDL.Text,
  'startDate' : IDL.Text,
});
export const BacktestStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Running' : IDL.Null,
  'Completed' : IDL.Null,
});
export const EquityPoint = IDL.Record({
  'value' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const BacktestResults = IDL.Record({
  'totalTrades' : IDL.Nat,
  'trades' : IDL.Vec(
    IDL.Record({
      'id' : IDL.Text,
      'pnl' : IDL.Opt(IDL.Float64),
      'status' : IDL.Variant({
        'Open' : IDL.Null,
        'Closed' : IDL.Null,
        'TakeProfitHit' : IDL.Null,
        'StopLossHit' : IDL.Null,
        'Cancelled' : IDL.Null,
      }),
      'action' : IDL.Variant({
        'Buy' : IDL.Null,
        'Hold' : IDL.Null,
        'Sell' : IDL.Null,
        'Skip' : IDL.Null,
      }),
      'closeTime' : IDL.Int,
      'pnlPercent' : IDL.Opt(IDL.Float64),
      'decisionId' : IDL.Text,
      'takeProfit' : IDL.Opt(IDL.Float64),
      'stopLoss' : IDL.Float64,
      'quantity' : IDL.Float64,
      'entryPrice' : IDL.Float64,
      'exitPrice' : IDL.Opt(IDL.Float64),
      'openTime' : IDL.Int,
      'symbol' : IDL.Text,
    })
  ),
  'sharpeRatio' : IDL.Opt(IDL.Float64),
  'finalBalance' : IDL.Float64,
  'equityCurve' : IDL.Vec(EquityPoint),
  'totalReturn' : IDL.Float64,
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'totalPnlPercent' : IDL.Float64,
});
export const BacktestSession = IDL.Record({
  'id' : IDL.Text,
  'status' : BacktestStatus,
  'initialBalance' : IDL.Float64,
  'symbols' : IDL.Vec(IDL.Text),
  'endDate' : IDL.Int,
  'name' : IDL.Text,
  'results' : IDL.Opt(BacktestResults),
  'startDate' : IDL.Int,
});
export const PartialExitLevel = IDL.Tuple(IDL.Float64, IDL.Float64);
export const SimulationFidelity = IDL.Record({
  'slippagePct' : IDL.Float64,
  'feeTakerPct' : IDL.Float64,
  'feeMakerPct' : IDL.Float64,
  'spreadPct' : IDL.Float64,
});
export const TradingMode = IDL.Variant({
  'Autonomous' : IDL.Null,
  'SignalOnly' : IDL.Null,
  'Manual' : IDL.Null,
});
export const BotConfig = IDL.Record({
  'partialExitLevels' : IDL.Vec(PartialExitLevel),
  'decisionIntervalSecs' : IDL.Nat,
  'simulationFidelity' : SimulationFidelity,
  'refreshIntervalSecs' : IDL.Nat,
  'startingBalance' : IDL.Float64,
  'tradingMode' : TradingMode,
  'volatilityPositionSizing' : IDL.Bool,
});
export const EquitySnapshot = IDL.Record({
  'dailyPnLPct' : IDL.Float64,
  'totalPnLPct' : IDL.Float64,
  'realizedPnLToday' : IDL.Float64,
  'cash' : IDL.Float64,
  'positionValue' : IDL.Float64,
  'timestamp' : IDL.Nat64,
  'unrealizedPnL' : IDL.Float64,
  'equity' : IDL.Float64,
});
export const DataFeedStatus = IDL.Record({
  'healthy' : IDL.Bool,
  'staleSince' : IDL.Opt(IDL.Nat64),
  'lastFetchAt' : IDL.Opt(IDL.Nat64),
  'assetCount' : IDL.Nat,
});
export const DecisionCycleStats = IDL.Record({
  'cyclesPerHour' : IDL.Float64,
  'totalCycles' : IDL.Nat,
  'avgConfidence' : IDL.Float64,
  'noTradeRate' : IDL.Float64,
  'tradesThisSession' : IDL.Nat,
  'winRate' : IDL.Float64,
});
export const AIDecisionLog = IDL.Record({
  'executionDetails' : IDL.Opt(
    IDL.Record({
      'slippagePct' : IDL.Float64,
      'feePct' : IDL.Float64,
      'executionDelayMs' : IDL.Nat,
      'spreadPct' : IDL.Float64,
    })
  ),
  'indicatorValues' : IDL.Record({
    'atr' : IDL.Float64,
    'rsi' : IDL.Float64,
    'bollingerBandwidth' : IDL.Float64,
    'macd' : IDL.Float64,
    'ema20' : IDL.Float64,
    'ema50' : IDL.Float64,
  }),
  'decision' : TradeDecision,
  'noTradeReason' : IDL.Opt(IDL.Text),
  'decisionCycleId' : IDL.Nat,
  'alternativesConsidered' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'skipReason' : IDL.Opt(IDL.Text),
  'executionStatus' : IDL.Variant({
    'Skipped' : IDL.Null,
    'Failed' : IDL.Null,
    'Executed' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'multiTimeframeSignals' : IDL.Vec(
    IDL.Record({
      'rsi' : IDL.Float64,
      'macdSignal' : IDL.Variant({
        'Bearish' : IDL.Null,
        'Cross' : IDL.Null,
        'Bullish' : IDL.Null,
      }),
      'trend' : IDL.Variant({
        'Bearish' : IDL.Null,
        'Neutral' : IDL.Null,
        'Bullish' : IDL.Null,
      }),
      'timeframe' : IDL.Text,
      'emaAlignment' : IDL.Bool,
      'strength' : IDL.Float64,
    })
  ),
  'marketSnapshot' : IDL.Record({
    'btcDominance' : IDL.Float64,
    'volume24h' : IDL.Float64,
    'volatilityPct' : IDL.Float64,
    'price' : IDL.Float64,
  }),
  'executedTradeId' : IDL.Opt(IDL.Text),
  'confidenceFactors' : IDL.Record({
    'regimeConfidence' : IDL.Float64,
    'total' : IDL.Float64,
    'trendAlignment' : IDL.Float64,
    'liquidity' : IDL.Float64,
    'momentum' : IDL.Float64,
    'marketStructure' : IDL.Float64,
    'historicalSetupPerformance' : IDL.Float64,
    'volatilityQuality' : IDL.Float64,
  }),
});
export const AssetBalance = IDL.Record({
  'asset' : IDL.Text,
  'free' : IDL.Float64,
  'locked' : IDL.Float64,
});
export const ExchangeStatus = IDL.Record({
  'exchangeId' : IDL.Text,
  'connected' : IDL.Bool,
  'phase' : IDL.Nat,
  'lastTestTimestamp' : IDL.Int,
});
export const OrderRecord = IDL.Record({
  'qty' : IDL.Float64,
  'status' : IDL.Text,
  'side' : IDL.Text,
  'orderId' : IDL.Text,
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const MarketSnapshot = IDL.Record({
  'btcDominance' : IDL.Float64,
  'totalMarketCap' : IDL.Float64,
  'markets' : IDL.Vec(MarketData),
  'timestamp' : IDL.Int,
  'fearGreedIndex' : IDL.Opt(IDL.Float64),
});
export const ActivityItem = IDL.Record({
  'action' : IDL.Text,
  'asset' : IDL.Text,
  'reasoning' : IDL.Text,
  'timestamp' : IDL.Nat64,
  'executed' : IDL.Bool,
  'confidence' : IDL.Float64,
});
export const Position = IDL.Record({
  'currentPrice' : IDL.Float64,
  'averageEntryPrice' : IDL.Float64,
  'takeProfit' : IDL.Opt(IDL.Float64),
  'stopLoss' : IDL.Float64,
  'unrealizedPnlPercent' : IDL.Float64,
  'quantity' : IDL.Float64,
  'unrealizedPnl' : IDL.Float64,
  'openTime' : IDL.Int,
  'symbol' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'totalTrades' : IDL.Nat,
  'dayPnl' : IDL.Float64,
  'dayPnlPercent' : IDL.Float64,
  'totalValue' : IDL.Float64,
  'totalPnl' : IDL.Float64,
  'cashBalance' : IDL.Float64,
  'winningTrades' : IDL.Nat,
  'positions' : IDL.Vec(Position),
  'winRate' : IDL.Float64,
  'totalPnlPercent' : IDL.Float64,
  'investedValue' : IDL.Float64,
});
export const RiskSeverity = IDL.Variant({
  'Info' : IDL.Null,
  'Critical' : IDL.Null,
  'Warning' : IDL.Null,
});
export const RiskEventType = IDL.Variant({
  'EmergencyStop' : IDL.Null,
  'VolatilityPause' : IDL.Null,
  'DailyLossLimitHit' : IDL.Null,
  'ManualPause' : IDL.Null,
  'ConsecutiveLossesAutopaused' : IDL.Null,
  'ResumeTrade' : IDL.Null,
});
export const RiskEvent = IDL.Record({
  'id' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : RiskSeverity,
  'eventType' : RiskEventType,
});
export const RiskSettings = IDL.Record({
  'conservativeMode' : IDL.Bool,
  'maxConsecutiveLosses' : IDL.Nat,
  'enablePaperTrading' : IDL.Bool,
  'emergencyStopEnabled' : IDL.Bool,
  'maxDailyLossPercent' : IDL.Float64,
  'maxPositionSizePercent' : IDL.Float64,
});
export const RiskStatus = IDL.Record({
  'dailyLoss' : IDL.Float64,
  'isPaused' : IDL.Bool,
  'consecutiveLosses' : IDL.Nat,
  'riskScore' : IDL.Float64,
  'dailyLossPercent' : IDL.Float64,
});
export const SimulationStats = IDL.Record({
  'avgSlippagePct' : IDL.Float64,
  'avgFeePct' : IDL.Float64,
  'totalSlippageCost' : IDL.Float64,
  'totalSpreadCost' : IDL.Float64,
  'totalFeeCost' : IDL.Float64,
});
export const StrategyPerformance = IDL.Record({
  'totalTrades' : IDL.Nat,
  'wins' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'avgConfidence' : IDL.Float64,
  'losses' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
  'strategyMode' : StrategyMode,
});
export const TradeTag = IDL.Variant({
  'GoodScaling' : IDL.Null,
  'GoodDiscipline' : IDL.Null,
  'TextbookWin' : IDL.Null,
  'OvertradeLoss' : IDL.Null,
  'RegimeMismatch' : IDL.Null,
  'PrematureExit' : IDL.Null,
  'TightStop' : IDL.Null,
});
export const TradeId = IDL.Text;
export const TechnicalIndicators = IDL.Record({
  'atr' : IDL.Float64,
  'rsi' : IDL.Float64,
  'macdSignal' : IDL.Float64,
  'bollingerMid' : IDL.Float64,
  'trendStrength' : IDL.Float64,
  'macd' : IDL.Float64,
  'momentum' : IDL.Float64,
  'bollingerLower' : IDL.Float64,
  'ema20' : IDL.Float64,
  'ema50' : IDL.Float64,
  'bollingerUpper' : IDL.Float64,
});
export const ConfidenceFactors = IDL.Record({
  'regimeConfidence' : IDL.Float64,
  'total' : IDL.Float64,
  'trendAlignment' : IDL.Float64,
  'liquidity' : IDL.Float64,
  'momentum' : IDL.Float64,
  'marketStructure' : IDL.Float64,
  'historicalSetupPerformance' : IDL.Float64,
  'volatilityQuality' : IDL.Float64,
});
export const TradeSnapshot = IDL.Record({
  'netImpactPct' : IDL.Float64,
  'marketRegimeAtEntry' : MarketCondition,
  'simulatedSpread' : IDL.Float64,
  'simulatedLatencyMs' : IDL.Nat,
  'tags' : IDL.Vec(TradeTag),
  'aiReasoningText' : IDL.Text,
  'tradeId' : TradeId,
  'indicatorsAtEntry' : TechnicalIndicators,
  'simulatedFees' : IDL.Float64,
  'simulatedSlippage' : IDL.Float64,
  'volatilityRatio' : IDL.Float64,
  'confidenceFactors' : ConfidenceFactors,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'applyTradeToTraining' : IDL.Func([Trade, TradeDecision], [], ['oneway']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backtestTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'botTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'closePosition' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Trade, 'err' : IDL.Text })],
      [],
    ),
  'emergencyStopBot' : IDL.Func([], [BotState], []),
  'executeManualTrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : Trade, 'err' : IDL.Text })],
      [],
    ),
  'executePendingDecisions' : IDL.Func([], [IDL.Vec(Trade)], []),
  'fetchAndStoreHistoricalCandles' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'fetchMarketData' : IDL.Func([], [IDL.Vec(MarketData)], []),
  'getAIStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'mode' : IDL.Text,
          'lastRunTime' : IDL.Int,
          'nextRunTime' : IDL.Int,
          'isRunning' : IDL.Bool,
          'cycleCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAITrainingState' : IDL.Func([], [AITrainingState], ['query']),
  'getAllConfidenceTimeline' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ConfidencePoint)],
      ['query'],
    ),
  'getArenaResults' : IDL.Func([IDL.Text], [IDL.Opt(ArenaSession)], ['query']),
  'getArenaSessions' : IDL.Func([], [IDL.Vec(ArenaSession)], ['query']),
  'getBacktestSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BacktestSession)],
      ['query'],
    ),
  'getBotConfig' : IDL.Func([], [BotConfig], ['query']),
  'getBotState' : IDL.Func([], [BotState], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfidenceTimeline' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ConfidencePoint)],
      ['query'],
    ),
  'getCurrentEquity' : IDL.Func([], [IDL.Opt(EquitySnapshot)], ['query']),
  'getCurrentMarketCondition' : IDL.Func(
      [],
      [IDL.Opt(MarketCondition)],
      ['query'],
    ),
  'getDataFeedStatus' : IDL.Func([], [DataFeedStatus], ['query']),
  'getDecisionCycleStats' : IDL.Func([], [DecisionCycleStats], ['query']),
  'getDecisionsByAsset' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(AIDecisionLog)],
      ['query'],
    ),
  'getEquityHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EquitySnapshot)],
      ['query'],
    ),
  'getExchangeBalances' : IDL.Func([IDL.Text], [IDL.Vec(AssetBalance)], []),
  'getExchangeConnections' : IDL.Func([], [IDL.Vec(ExchangeStatus)], ['query']),
  'getExchangeOrderHistory' : IDL.Func([IDL.Text], [IDL.Vec(OrderRecord)], []),
  'getHistoricalCandles' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Candle)], []),
  'getLatestDecisions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AIDecisionLog)],
      ['query'],
    ),
  'getLatestSnapshot' : IDL.Func([], [IDL.Opt(MarketSnapshot)], ['query']),
  'getLiveActivityFeed' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityItem)],
      ['query'],
    ),
  'getMarketCandles' : IDL.Func([IDL.Text], [IDL.Vec(Candle)], ['query']),
  'getMarketMemory' : IDL.Func(
      [],
      [IDL.Vec(StrategyPerformanceByRegime)],
      ['query'],
    ),
  'getNoTradeLog' : IDL.Func([], [IDL.Vec(NoTradeDecision)], ['query']),
  'getOpenPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getRecentDecisions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AIDecisionLog)],
      ['query'],
    ),
  'getRiskEvents' : IDL.Func([IDL.Nat], [IDL.Vec(RiskEvent)], ['query']),
  'getRiskSettings' : IDL.Func([], [RiskSettings], ['query']),
  'getRiskStatus' : IDL.Func([], [RiskStatus], ['query']),
  'getSimulationStats' : IDL.Func([], [SimulationStats], ['query']),
  'getStrategyPerformances' : IDL.Func(
      [],
      [IDL.Vec(StrategyPerformance)],
      ['query'],
    ),
  'getTopSetups' : IDL.Func(
      [],
      [IDL.Vec(StrategyPerformanceByRegime)],
      ['query'],
    ),
  'getTradeHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
  'getTradeSnapshot' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TradeSnapshot)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBacktestSessions' : IDL.Func([], [IDL.Vec(BacktestSession)], ['query']),
  'pauseBot' : IDL.Func([], [BotState], []),
  'refreshGlobalData' : IDL.Func([], [IDL.Float64, IDL.Float64], []),
  'removeExchangeConnection' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'resetBot' : IDL.Func([], [BotState], []),
  'resetTrainingData' : IDL.Func([], [IDL.Bool], []),
  'resumeBot' : IDL.Func([], [BotState], []),
  'resumeTrading' : IDL.Func([], [IDL.Bool], []),
  'runAIAnalysis' : IDL.Func([], [IDL.Vec(AIDecisionLog)], []),
  'runDecisionCycle' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'skipped' : IDL.Nat,
            'reasoning' : IDL.Text,
            'decisionsGenerated' : IDL.Nat,
            'positionsUpdated' : IDL.Nat,
            'tradesExecuted' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'runMarketCycle' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveExchangeConnection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setAIMode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'startArena' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'startBacktest' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Int, IDL.Int, IDL.Float64],
      [BacktestSession],
      [],
    ),
  'startBot' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : BotState, 'err' : IDL.Text })],
      [],
    ),
  'testExchangeConnection' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerEmergencyStop' : IDL.Func([], [IDL.Bool], []),
  'updateBotConfig' : IDL.Func(
      [BotConfig],
      [IDL.Variant({ 'ok' : BotConfig, 'err' : IDL.Text })],
      [],
    ),
  'updateRiskSettings' : IDL.Func([RiskSettings], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TradeStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'TakeProfitHit' : IDL.Null,
    'StopLossHit' : IDL.Null,
    'Cancelled' : IDL.Null,
  });
  const TradeAction = IDL.Variant({
    'Buy' : IDL.Null,
    'Hold' : IDL.Null,
    'Sell' : IDL.Null,
    'Skip' : IDL.Null,
  });
  const Trade = IDL.Record({
    'id' : IDL.Text,
    'pnl' : IDL.Opt(IDL.Float64),
    'status' : TradeStatus,
    'action' : TradeAction,
    'closeTime' : IDL.Int,
    'pnlPercent' : IDL.Opt(IDL.Float64),
    'decisionId' : IDL.Text,
    'takeProfit' : IDL.Opt(IDL.Float64),
    'stopLoss' : IDL.Float64,
    'quantity' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Opt(IDL.Float64),
    'openTime' : IDL.Int,
    'symbol' : IDL.Text,
  });
  const StrategyMode = IDL.Variant({
    'Defensive' : IDL.Null,
    'Observation' : IDL.Null,
    'TrendFollowing' : IDL.Null,
    'Scalping' : IDL.Null,
    'MeanReversion' : IDL.Null,
  });
  const TradeDecision = IDL.Record({
    'id' : IDL.Text,
    'action' : TradeAction,
    'marketCondition' : IDL.Variant({
      'StrongBearish' : IDL.Null,
      'LowLiquidityDanger' : IDL.Null,
      'HighVolatility' : IDL.Null,
      'ManipulationRisk' : IDL.Null,
      'Ranging' : IDL.Null,
      'Neutral' : IDL.Null,
      'WeakBearish' : IDL.Null,
      'StrongBullish' : IDL.Null,
      'Bullish' : IDL.Null,
    }),
    'targetPrice' : IDL.Opt(IDL.Float64),
    'reasoning' : IDL.Text,
    'riskReward' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'indicators' : IDL.Record({
      'atr' : IDL.Float64,
      'rsi' : IDL.Float64,
      'macdSignal' : IDL.Float64,
      'bollingerMid' : IDL.Float64,
      'trendStrength' : IDL.Float64,
      'macd' : IDL.Float64,
      'momentum' : IDL.Float64,
      'bollingerLower' : IDL.Float64,
      'ema20' : IDL.Float64,
      'ema50' : IDL.Float64,
      'bollingerUpper' : IDL.Float64,
    }),
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Float64,
    'confidence' : IDL.Float64,
    'strategyMode' : StrategyMode,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const BotStatus = IDL.Variant({
    'Stopped' : IDL.Null,
    'Paused' : IDL.Null,
    'EmergencyStopped' : IDL.Null,
    'Running' : IDL.Null,
  });
  const BotState = IDL.Record({
    'status' : BotStatus,
    'startedAt' : IDL.Opt(IDL.Nat64),
    'dataFeedHealthy' : IDL.Bool,
    'uptimeSeconds' : IDL.Nat64,
    'tradesExecutedCount' : IDL.Nat,
    'lastDecisionAt' : IDL.Opt(IDL.Nat64),
    'decisionCycleCount' : IDL.Nat,
    'lastDataFetchAt' : IDL.Opt(IDL.Nat64),
  });
  const MarketData = IDL.Record({
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'volume24h' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const CorrelationData = IDL.Record({
    'lastUpdated' : IDL.Int,
    'btcCorrelation' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MarketCondition = IDL.Variant({
    'StrongBearish' : IDL.Null,
    'LowLiquidityDanger' : IDL.Null,
    'HighVolatility' : IDL.Null,
    'ManipulationRisk' : IDL.Null,
    'Ranging' : IDL.Null,
    'Neutral' : IDL.Null,
    'WeakBearish' : IDL.Null,
    'StrongBullish' : IDL.Null,
    'Bullish' : IDL.Null,
  });
  const StrategyPerformanceByRegime = IDL.Record({
    'lossCount' : IDL.Nat,
    'marketCondition' : MarketCondition,
    'totalPnl' : IDL.Float64,
    'winCount' : IDL.Nat,
    'avgHoldTimeSeconds' : IDL.Int,
    'strategyMode' : StrategyMode,
    'avgPnl' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const Symbol = IDL.Text;
  const NoTradeReason = IDL.Variant({
    'OvertradingFlag' : IDL.Null,
    'ExistingPosition' : IDL.Null,
    'DrawdownProtection' : IDL.Null,
    'VolatilityTooHigh' : IDL.Null,
    'RegimeMismatch' : IDL.Null,
    'CorrelationLimit' : IDL.Null,
    'LiquidityTooLow' : IDL.Null,
    'LowConfidence' : IDL.Null,
  });
  const NoTradeDecision = IDL.Record({
    'marketRegime' : MarketCondition,
    'confidenceAtTime' : IDL.Float64,
    'thresholdAtTime' : IDL.Float64,
    'timestamp' : Timestamp,
    'symbol' : Symbol,
    'reason' : NoTradeReason,
  });
  const AITrainingState = IDL.Record({
    'confidenceThreshold' : IDL.Float64,
    'correlationData' : IDL.Vec(CorrelationData),
    'marketMemory' : IDL.Vec(StrategyPerformanceByRegime),
    'lastTrainingUpdate' : IDL.Int,
    'avgConfidenceScore' : IDL.Float64,
    'consecutiveLosses' : IDL.Nat,
    'strategyPerformances' : IDL.Vec(
      IDL.Record({
        'totalTrades' : IDL.Nat,
        'wins' : IDL.Nat,
        'lastUpdated' : IDL.Int,
        'avgConfidence' : IDL.Float64,
        'losses' : IDL.Nat,
        'totalPnl' : IDL.Float64,
        'winRate' : IDL.Float64,
        'strategyMode' : IDL.Variant({
          'Defensive' : IDL.Null,
          'Observation' : IDL.Null,
          'TrendFollowing' : IDL.Null,
          'Scalping' : IDL.Null,
          'MeanReversion' : IDL.Null,
        }),
      })
    ),
    'overallWinRate' : IDL.Float64,
    'learningProgress' : IDL.Float64,
    'confidenceCalibration' : IDL.Float64,
    'overtradingCount' : IDL.Nat,
    'practiceTradesCount' : IDL.Nat,
    'totalSessions' : IDL.Nat,
    'noTradeLog' : IDL.Vec(NoTradeDecision),
  });
  const ConfidencePoint = IDL.Record({
    'regime' : IDL.Text,
    'action' : IDL.Text,
    'asset' : IDL.Text,
    'timestamp' : IDL.Nat64,
    'confidence' : IDL.Float64,
  });
  const RegimeBreakdown = IDL.Record({
    'regime' : MarketCondition,
    'returnPct' : IDL.Float64,
    'winRate' : IDL.Float64,
  });
  const ArenaResult = IDL.Record({
    'tradeCount' : IDL.Nat,
    'agentId' : IDL.Text,
    'avgHoldTime' : IDL.Int,
    'sharpeRatio' : IDL.Float64,
    'performanceByRegime' : IDL.Vec(RegimeBreakdown),
    'finalBalance' : IDL.Float64,
    'winRate' : IDL.Float64,
    'totalReturnPct' : IDL.Float64,
    'maxDrawdownPct' : IDL.Float64,
  });
  const ArenaSession = IDL.Record({
    'completedAt' : IDL.Int,
    'endDate' : IDL.Text,
    'results' : IDL.Vec(ArenaResult),
    'initialCapital' : IDL.Float64,
    'sessionId' : IDL.Text,
    'symbol' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const BacktestStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Running' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const EquityPoint = IDL.Record({
    'value' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const BacktestResults = IDL.Record({
    'totalTrades' : IDL.Nat,
    'trades' : IDL.Vec(
      IDL.Record({
        'id' : IDL.Text,
        'pnl' : IDL.Opt(IDL.Float64),
        'status' : IDL.Variant({
          'Open' : IDL.Null,
          'Closed' : IDL.Null,
          'TakeProfitHit' : IDL.Null,
          'StopLossHit' : IDL.Null,
          'Cancelled' : IDL.Null,
        }),
        'action' : IDL.Variant({
          'Buy' : IDL.Null,
          'Hold' : IDL.Null,
          'Sell' : IDL.Null,
          'Skip' : IDL.Null,
        }),
        'closeTime' : IDL.Int,
        'pnlPercent' : IDL.Opt(IDL.Float64),
        'decisionId' : IDL.Text,
        'takeProfit' : IDL.Opt(IDL.Float64),
        'stopLoss' : IDL.Float64,
        'quantity' : IDL.Float64,
        'entryPrice' : IDL.Float64,
        'exitPrice' : IDL.Opt(IDL.Float64),
        'openTime' : IDL.Int,
        'symbol' : IDL.Text,
      })
    ),
    'sharpeRatio' : IDL.Opt(IDL.Float64),
    'finalBalance' : IDL.Float64,
    'equityCurve' : IDL.Vec(EquityPoint),
    'totalReturn' : IDL.Float64,
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'totalPnlPercent' : IDL.Float64,
  });
  const BacktestSession = IDL.Record({
    'id' : IDL.Text,
    'status' : BacktestStatus,
    'initialBalance' : IDL.Float64,
    'symbols' : IDL.Vec(IDL.Text),
    'endDate' : IDL.Int,
    'name' : IDL.Text,
    'results' : IDL.Opt(BacktestResults),
    'startDate' : IDL.Int,
  });
  const PartialExitLevel = IDL.Tuple(IDL.Float64, IDL.Float64);
  const SimulationFidelity = IDL.Record({
    'slippagePct' : IDL.Float64,
    'feeTakerPct' : IDL.Float64,
    'feeMakerPct' : IDL.Float64,
    'spreadPct' : IDL.Float64,
  });
  const TradingMode = IDL.Variant({
    'Autonomous' : IDL.Null,
    'SignalOnly' : IDL.Null,
    'Manual' : IDL.Null,
  });
  const BotConfig = IDL.Record({
    'partialExitLevels' : IDL.Vec(PartialExitLevel),
    'decisionIntervalSecs' : IDL.Nat,
    'simulationFidelity' : SimulationFidelity,
    'refreshIntervalSecs' : IDL.Nat,
    'startingBalance' : IDL.Float64,
    'tradingMode' : TradingMode,
    'volatilityPositionSizing' : IDL.Bool,
  });
  const EquitySnapshot = IDL.Record({
    'dailyPnLPct' : IDL.Float64,
    'totalPnLPct' : IDL.Float64,
    'realizedPnLToday' : IDL.Float64,
    'cash' : IDL.Float64,
    'positionValue' : IDL.Float64,
    'timestamp' : IDL.Nat64,
    'unrealizedPnL' : IDL.Float64,
    'equity' : IDL.Float64,
  });
  const DataFeedStatus = IDL.Record({
    'healthy' : IDL.Bool,
    'staleSince' : IDL.Opt(IDL.Nat64),
    'lastFetchAt' : IDL.Opt(IDL.Nat64),
    'assetCount' : IDL.Nat,
  });
  const DecisionCycleStats = IDL.Record({
    'cyclesPerHour' : IDL.Float64,
    'totalCycles' : IDL.Nat,
    'avgConfidence' : IDL.Float64,
    'noTradeRate' : IDL.Float64,
    'tradesThisSession' : IDL.Nat,
    'winRate' : IDL.Float64,
  });
  const AIDecisionLog = IDL.Record({
    'executionDetails' : IDL.Opt(
      IDL.Record({
        'slippagePct' : IDL.Float64,
        'feePct' : IDL.Float64,
        'executionDelayMs' : IDL.Nat,
        'spreadPct' : IDL.Float64,
      })
    ),
    'indicatorValues' : IDL.Record({
      'atr' : IDL.Float64,
      'rsi' : IDL.Float64,
      'bollingerBandwidth' : IDL.Float64,
      'macd' : IDL.Float64,
      'ema20' : IDL.Float64,
      'ema50' : IDL.Float64,
    }),
    'decision' : TradeDecision,
    'noTradeReason' : IDL.Opt(IDL.Text),
    'decisionCycleId' : IDL.Nat,
    'alternativesConsidered' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'skipReason' : IDL.Opt(IDL.Text),
    'executionStatus' : IDL.Variant({
      'Skipped' : IDL.Null,
      'Failed' : IDL.Null,
      'Executed' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'multiTimeframeSignals' : IDL.Vec(
      IDL.Record({
        'rsi' : IDL.Float64,
        'macdSignal' : IDL.Variant({
          'Bearish' : IDL.Null,
          'Cross' : IDL.Null,
          'Bullish' : IDL.Null,
        }),
        'trend' : IDL.Variant({
          'Bearish' : IDL.Null,
          'Neutral' : IDL.Null,
          'Bullish' : IDL.Null,
        }),
        'timeframe' : IDL.Text,
        'emaAlignment' : IDL.Bool,
        'strength' : IDL.Float64,
      })
    ),
    'marketSnapshot' : IDL.Record({
      'btcDominance' : IDL.Float64,
      'volume24h' : IDL.Float64,
      'volatilityPct' : IDL.Float64,
      'price' : IDL.Float64,
    }),
    'executedTradeId' : IDL.Opt(IDL.Text),
    'confidenceFactors' : IDL.Record({
      'regimeConfidence' : IDL.Float64,
      'total' : IDL.Float64,
      'trendAlignment' : IDL.Float64,
      'liquidity' : IDL.Float64,
      'momentum' : IDL.Float64,
      'marketStructure' : IDL.Float64,
      'historicalSetupPerformance' : IDL.Float64,
      'volatilityQuality' : IDL.Float64,
    }),
  });
  const AssetBalance = IDL.Record({
    'asset' : IDL.Text,
    'free' : IDL.Float64,
    'locked' : IDL.Float64,
  });
  const ExchangeStatus = IDL.Record({
    'exchangeId' : IDL.Text,
    'connected' : IDL.Bool,
    'phase' : IDL.Nat,
    'lastTestTimestamp' : IDL.Int,
  });
  const OrderRecord = IDL.Record({
    'qty' : IDL.Float64,
    'status' : IDL.Text,
    'side' : IDL.Text,
    'orderId' : IDL.Text,
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const MarketSnapshot = IDL.Record({
    'btcDominance' : IDL.Float64,
    'totalMarketCap' : IDL.Float64,
    'markets' : IDL.Vec(MarketData),
    'timestamp' : IDL.Int,
    'fearGreedIndex' : IDL.Opt(IDL.Float64),
  });
  const ActivityItem = IDL.Record({
    'action' : IDL.Text,
    'asset' : IDL.Text,
    'reasoning' : IDL.Text,
    'timestamp' : IDL.Nat64,
    'executed' : IDL.Bool,
    'confidence' : IDL.Float64,
  });
  const Position = IDL.Record({
    'currentPrice' : IDL.Float64,
    'averageEntryPrice' : IDL.Float64,
    'takeProfit' : IDL.Opt(IDL.Float64),
    'stopLoss' : IDL.Float64,
    'unrealizedPnlPercent' : IDL.Float64,
    'quantity' : IDL.Float64,
    'unrealizedPnl' : IDL.Float64,
    'openTime' : IDL.Int,
    'symbol' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'totalTrades' : IDL.Nat,
    'dayPnl' : IDL.Float64,
    'dayPnlPercent' : IDL.Float64,
    'totalValue' : IDL.Float64,
    'totalPnl' : IDL.Float64,
    'cashBalance' : IDL.Float64,
    'winningTrades' : IDL.Nat,
    'positions' : IDL.Vec(Position),
    'winRate' : IDL.Float64,
    'totalPnlPercent' : IDL.Float64,
    'investedValue' : IDL.Float64,
  });
  const RiskSeverity = IDL.Variant({
    'Info' : IDL.Null,
    'Critical' : IDL.Null,
    'Warning' : IDL.Null,
  });
  const RiskEventType = IDL.Variant({
    'EmergencyStop' : IDL.Null,
    'VolatilityPause' : IDL.Null,
    'DailyLossLimitHit' : IDL.Null,
    'ManualPause' : IDL.Null,
    'ConsecutiveLossesAutopaused' : IDL.Null,
    'ResumeTrade' : IDL.Null,
  });
  const RiskEvent = IDL.Record({
    'id' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : RiskSeverity,
    'eventType' : RiskEventType,
  });
  const RiskSettings = IDL.Record({
    'conservativeMode' : IDL.Bool,
    'maxConsecutiveLosses' : IDL.Nat,
    'enablePaperTrading' : IDL.Bool,
    'emergencyStopEnabled' : IDL.Bool,
    'maxDailyLossPercent' : IDL.Float64,
    'maxPositionSizePercent' : IDL.Float64,
  });
  const RiskStatus = IDL.Record({
    'dailyLoss' : IDL.Float64,
    'isPaused' : IDL.Bool,
    'consecutiveLosses' : IDL.Nat,
    'riskScore' : IDL.Float64,
    'dailyLossPercent' : IDL.Float64,
  });
  const SimulationStats = IDL.Record({
    'avgSlippagePct' : IDL.Float64,
    'avgFeePct' : IDL.Float64,
    'totalSlippageCost' : IDL.Float64,
    'totalSpreadCost' : IDL.Float64,
    'totalFeeCost' : IDL.Float64,
  });
  const StrategyPerformance = IDL.Record({
    'totalTrades' : IDL.Nat,
    'wins' : IDL.Nat,
    'lastUpdated' : IDL.Int,
    'avgConfidence' : IDL.Float64,
    'losses' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
    'strategyMode' : StrategyMode,
  });
  const TradeTag = IDL.Variant({
    'GoodScaling' : IDL.Null,
    'GoodDiscipline' : IDL.Null,
    'TextbookWin' : IDL.Null,
    'OvertradeLoss' : IDL.Null,
    'RegimeMismatch' : IDL.Null,
    'PrematureExit' : IDL.Null,
    'TightStop' : IDL.Null,
  });
  const TradeId = IDL.Text;
  const TechnicalIndicators = IDL.Record({
    'atr' : IDL.Float64,
    'rsi' : IDL.Float64,
    'macdSignal' : IDL.Float64,
    'bollingerMid' : IDL.Float64,
    'trendStrength' : IDL.Float64,
    'macd' : IDL.Float64,
    'momentum' : IDL.Float64,
    'bollingerLower' : IDL.Float64,
    'ema20' : IDL.Float64,
    'ema50' : IDL.Float64,
    'bollingerUpper' : IDL.Float64,
  });
  const ConfidenceFactors = IDL.Record({
    'regimeConfidence' : IDL.Float64,
    'total' : IDL.Float64,
    'trendAlignment' : IDL.Float64,
    'liquidity' : IDL.Float64,
    'momentum' : IDL.Float64,
    'marketStructure' : IDL.Float64,
    'historicalSetupPerformance' : IDL.Float64,
    'volatilityQuality' : IDL.Float64,
  });
  const TradeSnapshot = IDL.Record({
    'netImpactPct' : IDL.Float64,
    'marketRegimeAtEntry' : MarketCondition,
    'simulatedSpread' : IDL.Float64,
    'simulatedLatencyMs' : IDL.Nat,
    'tags' : IDL.Vec(TradeTag),
    'aiReasoningText' : IDL.Text,
    'tradeId' : TradeId,
    'indicatorsAtEntry' : TechnicalIndicators,
    'simulatedFees' : IDL.Float64,
    'simulatedSlippage' : IDL.Float64,
    'volatilityRatio' : IDL.Float64,
    'confidenceFactors' : ConfidenceFactors,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'applyTradeToTraining' : IDL.Func([Trade, TradeDecision], [], ['oneway']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backtestTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'botTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'closePosition' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Trade, 'err' : IDL.Text })],
        [],
      ),
    'emergencyStopBot' : IDL.Func([], [BotState], []),
    'executeManualTrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : Trade, 'err' : IDL.Text })],
        [],
      ),
    'executePendingDecisions' : IDL.Func([], [IDL.Vec(Trade)], []),
    'fetchAndStoreHistoricalCandles' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'fetchMarketData' : IDL.Func([], [IDL.Vec(MarketData)], []),
    'getAIStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'mode' : IDL.Text,
            'lastRunTime' : IDL.Int,
            'nextRunTime' : IDL.Int,
            'isRunning' : IDL.Bool,
            'cycleCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAITrainingState' : IDL.Func([], [AITrainingState], ['query']),
    'getAllConfidenceTimeline' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ConfidencePoint)],
        ['query'],
      ),
    'getArenaResults' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ArenaSession)],
        ['query'],
      ),
    'getArenaSessions' : IDL.Func([], [IDL.Vec(ArenaSession)], ['query']),
    'getBacktestSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BacktestSession)],
        ['query'],
      ),
    'getBotConfig' : IDL.Func([], [BotConfig], ['query']),
    'getBotState' : IDL.Func([], [BotState], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfidenceTimeline' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ConfidencePoint)],
        ['query'],
      ),
    'getCurrentEquity' : IDL.Func([], [IDL.Opt(EquitySnapshot)], ['query']),
    'getCurrentMarketCondition' : IDL.Func(
        [],
        [IDL.Opt(MarketCondition)],
        ['query'],
      ),
    'getDataFeedStatus' : IDL.Func([], [DataFeedStatus], ['query']),
    'getDecisionCycleStats' : IDL.Func([], [DecisionCycleStats], ['query']),
    'getDecisionsByAsset' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(AIDecisionLog)],
        ['query'],
      ),
    'getEquityHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EquitySnapshot)],
        ['query'],
      ),
    'getExchangeBalances' : IDL.Func([IDL.Text], [IDL.Vec(AssetBalance)], []),
    'getExchangeConnections' : IDL.Func(
        [],
        [IDL.Vec(ExchangeStatus)],
        ['query'],
      ),
    'getExchangeOrderHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderRecord)],
        [],
      ),
    'getHistoricalCandles' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Candle)],
        [],
      ),
    'getLatestDecisions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AIDecisionLog)],
        ['query'],
      ),
    'getLatestSnapshot' : IDL.Func([], [IDL.Opt(MarketSnapshot)], ['query']),
    'getLiveActivityFeed' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityItem)],
        ['query'],
      ),
    'getMarketCandles' : IDL.Func([IDL.Text], [IDL.Vec(Candle)], ['query']),
    'getMarketMemory' : IDL.Func(
        [],
        [IDL.Vec(StrategyPerformanceByRegime)],
        ['query'],
      ),
    'getNoTradeLog' : IDL.Func([], [IDL.Vec(NoTradeDecision)], ['query']),
    'getOpenPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getRecentDecisions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AIDecisionLog)],
        ['query'],
      ),
    'getRiskEvents' : IDL.Func([IDL.Nat], [IDL.Vec(RiskEvent)], ['query']),
    'getRiskSettings' : IDL.Func([], [RiskSettings], ['query']),
    'getRiskStatus' : IDL.Func([], [RiskStatus], ['query']),
    'getSimulationStats' : IDL.Func([], [SimulationStats], ['query']),
    'getStrategyPerformances' : IDL.Func(
        [],
        [IDL.Vec(StrategyPerformance)],
        ['query'],
      ),
    'getTopSetups' : IDL.Func(
        [],
        [IDL.Vec(StrategyPerformanceByRegime)],
        ['query'],
      ),
    'getTradeHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
    'getTradeSnapshot' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TradeSnapshot)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBacktestSessions' : IDL.Func(
        [],
        [IDL.Vec(BacktestSession)],
        ['query'],
      ),
    'pauseBot' : IDL.Func([], [BotState], []),
    'refreshGlobalData' : IDL.Func([], [IDL.Float64, IDL.Float64], []),
    'removeExchangeConnection' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'resetBot' : IDL.Func([], [BotState], []),
    'resetTrainingData' : IDL.Func([], [IDL.Bool], []),
    'resumeBot' : IDL.Func([], [BotState], []),
    'resumeTrading' : IDL.Func([], [IDL.Bool], []),
    'runAIAnalysis' : IDL.Func([], [IDL.Vec(AIDecisionLog)], []),
    'runDecisionCycle' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'skipped' : IDL.Nat,
              'reasoning' : IDL.Text,
              'decisionsGenerated' : IDL.Nat,
              'positionsUpdated' : IDL.Nat,
              'tradesExecuted' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'runMarketCycle' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveExchangeConnection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setAIMode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'startArena' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'startBacktest' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Int, IDL.Int, IDL.Float64],
        [BacktestSession],
        [],
      ),
    'startBot' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : BotState, 'err' : IDL.Text })],
        [],
      ),
    'testExchangeConnection' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerEmergencyStop' : IDL.Func([], [IDL.Bool], []),
    'updateBotConfig' : IDL.Func(
        [BotConfig],
        [IDL.Variant({ 'ok' : BotConfig, 'err' : IDL.Text })],
        [],
      ),
    'updateRiskSettings' : IDL.Func([RiskSettings], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };